#!/bin/bash

# Create a backup of the default Nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Configure Nginx to redirect /redirect_me with a 301 Moved Permanently
sudo sed -i '/location \/ {/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Reload Nginx to apply changes
sudo service nginx reload
